### 주요 라이브러리
- pandas : 데이터 처리 및 분석
- numpy : 과학계산 및 수학계산
    - C, C++ 로 작성됨
- scipy : 과학계산 및 통계
- tensorflow : 머신러닝, 딥러닝
- keras : 신경망, 딥러닝
- matplotlib, seaborn, plotly : 시각화

1. 넘파이 배열
- 벡터(1차원), 매트릭스(2차원)
- 머신러닝에서 사용하는 데이터 구조
- ndarray

In [1]:
import numpy as np

In [ ]:
# 1차원 배열 (벡터)

arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
arr1.shape

(3,)

In [8]:
# 2차원 배열 (매트릭스)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
arr3 = np.array([[1,2,3]])
print(arr3)
print(arr3.shape)

[[1 2 3]]
(1, 3)


In [11]:
print("차원 : ", arr1.ndim)
print("차원 : ", arr2.ndim)
print("차원 : ", arr3.ndim)

차원 :  1
차원 :  2
차원 :  2


In [13]:
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [15]:
print(arr1.dtype)
print(type(arr1))

int64
<class 'numpy.ndarray'>


In [16]:
arr1.astype('float64')

array([1., 2., 3.])

### 넘파이 배열 생성 함수

In [ ]:
# arange(숫자) : 0 ~ 숫자(미포함) 가 들어간 array 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [19]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [21]:
np.zeros(5, dtype='int64')

array([0, 0, 0, 0, 0])

In [22]:
np.zeros((2,3), dtype='int64')

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((2,5), dtype='int64')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.empty(4)

array([0.00000000e+000, 6.97737324e-312, 6.97733696e-312, 6.97737324e-312])

In [26]:
np.empty((3, 4), dtype='int64')

array([[    140714223081832,       1412272246320,                   0,
              1412272246320],
       [       214748364800,       1412272246320, 3256719575655383041,
                          0],
       [      1412272246320,       1412272246320,       1412272246320,
                          0]])

In [27]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [31]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
# 균등하게 분할된 값 반환
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# random : 0 <= x < 1
np.random.rand(2, 3)

array([[0.35996121, 0.57820086, 0.62937267],
       [0.09571581, 0.63490198, 0.55890105]])

In [34]:
# 정규분포로 샘플링된 값 반환

np.random.randn()

-0.1901777113701424

In [35]:
np.random.randn(5)

array([0.12496107, 0.09030001, 0.92354191, 1.04905967, 0.60862816])

In [ ]:
# 1 ~ 10 숫자 중에서 무작위로 5개 추출
np.random.randint(1, 10, 5)

array([3, 1, 5, 5, 2], dtype=int32)

In [ ]:
np.random.seed(25) # 25는 의미 없는 수, 아무 숫자나 들어가도 무관
np.random.randint(1,100, (3,5))

array([[94,  1, 33, 55, 45],
       [ 7, 36,  6, 40, 53],
       [85, 60, 60, 37, 14]], dtype=int32)

In [39]:
# 내가 지정한 숫자에서 뽑아주길 원한다면
arr1 = np.array([1,23,1.5,2.6,4.9])

# 여기만 있으면 0 ~ 100 사이 숫자 무작위로 뽑아냄
np.random.choice(arr1, (2,2))

array([[23. ,  2.6],
       [ 1. ,  1.5]])

In [40]:
# replace=False (중복없이 추출)
np.random.choice(arr1, (2,2), replace=False)

array([[23. ,  1. ],
       [ 1.5,  2.6]])

In [42]:
# 인덱싱, 슬라이싱 가능

arr1 = np.arange(1, 10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 1차원 슬라이싱
print(arr1[3])
print(arr1[3:])
print(arr1[3:8])

4
[4 5 6 7 8 9]
[4 5 6 7 8]


In [ ]:
# 1차원 => 2차원
arr2 = arr1.reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
# 2차원 슬라이싱
print(arr2[0])
print(arr2[0:2, 0:1])

[1 2 3]
[[1]
 [4]]


In [52]:
arr1[arr1 % 2 == 0]

array([2, 4, 6, 8])

In [53]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,1,1],[2,2,2]])

In [54]:
x + y

array([[2, 3, 4],
       [6, 7, 8]])

In [55]:
x - y

array([[0, 1, 2],
       [2, 3, 4]])

In [56]:
np.subtract(x,y)

array([[0, 1, 2],
       [2, 3, 4]])

In [57]:
print(x * y)
print(np.multiply(x, y))

[[ 1  2  3]
 [ 8 10 12]]
[[ 1  2  3]
 [ 8 10 12]]


In [58]:
print(x / y)
print(np.divide(x, y))

[[1.  2.  3. ]
 [2.  2.5 3. ]]
[[1.  2.  3. ]
 [2.  2.5 3. ]]


In [59]:
np.mean(x)

np.float64(3.5)

In [60]:
np.var(x)

np.float64(2.9166666666666665)